

setwd("/media/wa3j/Seagate2/Documents/PRO/adipogenesis/package/SM/degpca")
setwd(dir)

library(dplyr)
library(DESeq2)
library(ggplot2)
library(LSD)
library(VennDiagram)

#######################################################################################
## acquire data
## note. differential expression data were generated by pro_time_deg_ge.R and pro_time_deg_tu.R
## for largest interval gene annotations and inferred annotations, respectively
#######################################################################################

# out = list(deg=deg, deseq_obj=deseq_obj)
load("LRTres_pro_TU.RData")
deseq.tu = out$deseq_obj
rm(out)

load("LRTres_pro_GE.RData")
deseq.ge = out$deseq_obj
rm(out)

############################################################
## key analysis parameters
############################################################

# sig thresh for LRT
fc.thresh = 1
sigs = c(1e-6,1e-5,1e-4,1e-3,1e-2,1e-1)


############################################################
## loop through significance thresholds, make comparisons
############################################################

# gene ids
get.id = function(input=NULL){
  out = sapply(input,function(x){
    strsplit(x,"_")[[1]][2]
  })
  return(out)
}

# matching genes, indices, deg res
match.inds = function(match.ids=NULL, all.ids=NULL){
  inds = sapply(match.ids,function(x){
    which(all.ids == x)
  })
  return(inds)
}

# # deg loop
# res = data.frame(matrix(0,length(sigs),4))
# names(res) = c("fdr","sigtu","siggene","sigboth")
# res$fdr = sigs
# for(ii in 1:length(sigs)){
# 
#   # deg analysis
#   sig.thresh = sigs[ii]
#   deg.tu = DESeq(deseq.tu, test="LRT", full=~conditions,  reduced=~1)
#   deg.ge = DESeq(deseq.ge, test="LRT", full=~conditions,  reduced=~1)
#   res.tu = results(deg.tu) %>% as.data.frame(stringsAsFactors=F)
#   res.ge = results(deg.ge) %>% as.data.frame(stringsAsFactors=F)
# 
#   # gene matching
#   ids.tu = get.id( rownames(res.tu) )
#   ids.ge = get.id( rownames(res.ge) )
#   match.ids = ids.tu[ids.tu %in% ids.ge]
#   ind.tu = match.inds(match.ids=match.ids, all.ids=ids.tu)
#   ind.ge = match.inds(match.ids=match.ids, all.ids=ids.ge)
#   res.tu.match = res.tu[ind.tu,]
#   res.ge.match = res.ge[ind.ge,]
#   all(ids.tu[ind.tu] == ids.ge[ind.ge])
#   res.tu.match = res.tu.match %>% mutate(gene = ids.tu[ind.tu])
#   res.ge.match = res.ge.match %>% mutate(gene = ids.ge[ind.ge])
# 
#   # filter for significance
#   res.ge.match.sig = res.ge.match %>% filter(padj < sig.thresh)
#   res.tu.match.sig = res.tu.match %>% filter(padj < sig.thresh)
# 
#   # separate out different categories
#   ge.not.tu = res.ge.match.sig$gene[!(res.ge.match.sig$gene %in% res.tu.match.sig$gene)]
#   tu.not.ge = res.tu.match.sig$gene[!(res.tu.match.sig$gene %in% res.ge.match.sig$gene)]
#   ge.in.tu = res.ge.match.sig$gene[res.ge.match.sig$gene %in% res.tu.match.sig$gene]
#   tu.in.ge = res.tu.match.sig$gene[res.tu.match.sig$gene %in% res.ge.match.sig$gene]
# 
#   # venn diagram info
#   res$sigtu[ii] = length(tu.not.ge)
#   res$siggene[ii] = length(ge.not.tu)
#   res$sigboth[ii] = length(tu.in.ge)
# 
# } # ii loop

# save(res, file="compvaryp.RData")
# load("compvaryp.RData")

#######################################################################################
## plot data for fdr variation
#######################################################################################

pdf("fdrvar.pdf")
par(mfrow=c(2,3))
cex = 1
plot(log10(res$fdr), log10(res$sigboth), cex=cex, col="black")
points(log10(res$fdr), log10(res$sigboth), type="l", lwd=3, col="black")

c1 = "orange"
c2 = "purple"

ymin = log10( 0.9 * min(c(res$siggene, res$sigtu)) )
ymax = log10( 1.1 * max(c(res$siggene, res$sigtu)) )
ylim = c(ymin, ymax)
plot(log10(res$fdr), log10(res$sigtu), type="l", lwd=3, col=c1, ylim=ylim)
points(log10(res$fdr), log10(res$sigtu), cex=cex, col=c1)
points(log10(res$fdr), log10(res$siggene), type="l", lwd=3, col=c2)
points(log10(res$fdr), log10(res$siggene), cex=cex, col=c2)

dev.off()

#######################################################################################
## check significance
#######################################################################################

# binomial test for significance, all fdr
p.binom = apply(res,1,function(x){
  ntu = x[2] %>% as.numeric
  nge = x[3] %>% as.numeric
  bt = binom.test(ntu, ntu+nge)
  pb = bt$p.value
})

# binom test frds
fdr.binom = p.adjust(p.binom,method="BH")
max(fdr.binom)

# cbind(res,fdr.binom)
# fdr sigtu siggene sigboth    fdr.binom
# 1 1e-06   797     370   10413 1.048928e-35
# 2 1e-05   731     343   10701 2.142283e-32
# 3 1e-04   627     304   11020 3.060116e-26
# 4 1e-03   520     241   11351 3.157692e-24
# 5 1e-02   394     191   11663 3.900158e-17
# 6 1e-01   240     149   12020 4.584751e-06
